export const styles = {
  // Sesuaikan tinggi agar tidak melebihi layar karena ada padding container (24px * 2) + Header (64px)
  posLayout: { display: 'flex', height: 'calc(100vh - 120px)', backgroundColor: 'var(--bg-color)', color: 'var(--text-color)', overflow: 'hidden', borderRadius: '12px', border: '1px solid var(--border-color)' },
  posMenuPanel: { flex: 3, padding: '20px', display: 'flex', flexDirection: 'column', borderRight: '1px solid var(--border-color)' },
  posTitle: { margin: '0 0 20px 0', fontSize: '1.5rem', fontWeight: '700' },
  posCategoryList: { display: 'flex', gap: '10px', marginBottom: '20px', flexWrap: 'wrap' },
  categoryPill: { padding: '8px 16px', borderRadius: '20px', border: '1px solid var(--border-color)', backgroundColor: 'var(--card-bg)', cursor: 'pointer', transition: 'all 0.2s', fontSize: '0.9rem', fontWeight: '500' },
  categoryPillActive: { backgroundColor: 'var(--primary-color)', color: 'white', borderColor: 'var(--primary-color)' },
  // Gunakan minmax lebih kecil (130px) dan align-content start agar tidak renggang ke bawah
  posMenuGrid: { flex: 1, overflowY: 'auto', display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(130px, 1fr))', gap: '12px', paddingRight: '5px', alignContent: 'start' },
  posItemImageWrapper: { width: '100%', height: '80px', borderRadius: '6px', overflow: 'hidden', backgroundColor: 'var(--bg-color)', position: 'relative', marginBottom: '8px' },
  posItemImage: { width: '100%', height: '100%', objectFit: 'cover' },
  posItemPlaceholderImage: { fontSize: '3rem', display: 'flex', alignItems: 'center', justifyContent: 'center', height: '100%', color: 'var(--text-muted)' },
  posItemStockOverlay: { position: 'absolute', top: 0, left: 0, right: 0, bottom: 0, background: 'rgba(0,0,0,0.6)', color: 'white', display: 'flex', alignItems: 'center', justifyContent: 'center', fontWeight: 'bold', borderRadius: '8px' },
  posItemName: { fontWeight: '600', margin: '0 0 4px', fontSize: '0.85rem', lineHeight: '1.2', whiteSpace: 'nowrap', overflow: 'hidden', textOverflow: 'ellipsis' },
  posItemPrice: { color: 'var(--success-color)', fontWeight: 'bold', margin: 0, fontSize: '0.85rem' },
  posCartPanel: { flex: 2, minWidth: '400px', backgroundColor: 'var(--card-bg)', padding: '24px', display: 'flex', flexDirection: 'column', boxShadow: '-5px 0 25px rgba(0,0,0,0.05)', borderLeft: '1px solid var(--border-color)' },
  posCartHeader: { display: 'flex', flexDirection: 'column', gap: '16px', borderBottom: '1px solid var(--border-color)', paddingBottom: '20px' },
  posCartHeaderTop: { display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start' },
  posCartHeaderActions: { display: 'grid', gridTemplateColumns: '1fr 1fr 1fr 1fr', gap: '10px' },
  headerActionBtn: { display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', gap: '4px', padding: '10px 5px', borderRadius: '8px', border: '1px solid var(--border-color)', background: 'var(--bg-color)', color: 'var(--text-color)', fontSize: '0.75rem', fontWeight: '600', cursor: 'pointer', transition: 'all 0.2s', width: '100%' },
  posCartHeaderTitle: { margin: 0, fontSize: '1.2rem', fontWeight: '600' },
  posCartList: { flex: 1, overflowY: 'auto', margin: '20px 0', paddingRight: '5px' },
  posCartEmpty: { textAlign: 'center', color: 'var(--text-muted)', paddingTop: '40px', fontSize: '0.9rem' },
  posCartItem: { display: 'flex', alignItems: 'center', marginBottom: '15px', gap: '10px' },
  posCartItemDetails: { flex: 1 },
  posCartItemName: { margin: 0, fontWeight: '600', fontSize: '0.95rem' },
  posCartItemPrice: { margin: '5px 0 0', color: 'var(--text-muted)', fontSize: '0.85rem' },
  posCartItemActions: { display: 'flex', alignItems: 'center', gap: '10px' },
  posQtyBtn: { width: '30px', height: '30px', border: '1px solid var(--border-color)', backgroundColor: 'var(--bg-color)', cursor: 'pointer', borderRadius: '6px', fontWeight: 'bold', display: 'flex', alignItems: 'center', justifyContent: 'center', lineHeight: 1 },
  posQtyValue: { fontWeight: 'bold', minWidth: '20px', textAlign: 'center' },
  posRemoveBtn: { marginLeft: '10px', color: 'var(--danger-color)', background: 'none', border: 'none', cursor: 'pointer', fontSize: '1.2rem' },
  posCartSummary: { borderTop: '1px solid var(--border-color)', paddingTop: '20px' },
  posCartItemNote: { fontSize: '0.8rem', color: 'var(--primary-color)', fontStyle: 'italic', background: 'var(--primary-color-light)', padding: '4px 8px', borderRadius: '4px', marginTop: '5px' },
  posEditNoteBtn: { background: 'none', border: 'none', cursor: 'pointer', fontSize: '1.5rem', color: 'var(--text-muted)' },
  posSummaryRow: { display: 'flex', justifyContent: 'space-between', marginBottom: '12px', fontSize: '0.95rem' },
  posSummaryRowTax: { color: 'var(--text-muted)' },
  posSummaryRowTotal: { fontWeight: 'bold', fontSize: '1.3rem', marginTop: '15px', color: 'var(--primary-color)' },
  posCartButtons: { display: 'flex', gap: '10px', marginTop: '20px' },
  posBtn: { padding: '12px', border: 'none', borderRadius: '8px', fontWeight: 'bold', cursor: 'pointer', flex: 1, fontSize: '0.9rem' },
  posBtnHold: { backgroundColor: 'var(--warning-color)', color: 'white' },
  posBtnCancel: { backgroundColor: 'var(--danger-color)', color: 'white' },
  posBtnPay: { width: '100%', marginTop: '10px', backgroundColor: 'var(--success-color)', color: 'white', fontSize: '1.1rem', padding: '14px' },
  posBtnSecondary: { backgroundColor: 'var(--bg-color)', color: 'var(--text-color)', border: '1px solid var(--border-color)' },
  heldCartsContainer: { position: 'relative' },
  discountInput: { padding: '8px 12px', border: '1px solid var(--border-color)', borderRadius: '6px', width: '100px', textAlign: 'right', boxSizing: 'border-box' },
  discountTypeBtn: { padding: '8px', border: '1px solid var(--border-color)', background: 'var(--bg-color)', cursor: 'pointer' },
  heldCartsDropdown: { position: 'absolute', top: '100%', right: 0, backgroundColor: 'var(--card-bg)', border: '1px solid var(--border-color)', borderRadius: '8px', boxShadow: '0 4px 10px rgba(0,0,0,0.1)', zIndex: 10, width: '250px' },
  heldCartsDropdownItem: { padding: '12px', cursor: 'pointer', borderBottom: '1px solid var(--border-color)' },
  paymentMethod: { display: 'flex', flexDirection: 'column', alignItems: 'center', gap: '10px', padding: '20px', borderRadius: '8px', cursor: 'pointer', fontWeight: 'bold', border: '1px solid var(--border-color)', backgroundColor: 'var(--bg-color)', color: 'var(--text-color)', transition: 'all 0.2s' },
};